"$schema" = 'https://starship.rs/config-schema.json'

[aws]
style = "white"

[character]
success_symbol = "❯"

[directory]
style = "white"

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
style = "white"
format = "on [$symbol$branch]($style) "

[git_commit]
style = "white"

[git_metrics]
disabled = false

[git_state]
style = "bold dimmed white"

[git_status]
style = "white"

[haskell]
style = "white"

[java]
style = "white"

[nix_shell]
style = "white"

[nodejs]
style = "white"

[purescript]
style = "white"

[ruby]
style = "white"
