tap 'caskroom/cask'
tap 'homebrew/bundle'
brew 'cmigemo', args: ['HEAD']
brew 'tup'
cask 'appcleaner'
cask 'aquaskk'
cask 'docker'
cask 'emacs'
cask 'java'
cask 'karabiner-elements'
cask 'osxfuse'
cask 'slack'
cask 'xquartz'
cask 'yujitach-menumeters'
