#! /usr/bin/env sh

set -eux

update_straight_lockfile () {
    lockfile=~/.config/emacs/straight/versions/default.el
    lockfile_dotfiles=./module/emacs/default.el

    [ -f $lockfile ] && rm $lockfile
    emacsclient --eval '(straight-freeze-versions)'
    mv $lockfile $lockfile_dotfiles
    home-manager switch
    jj commit --message 'Emacs: update straight lockfile' $lockfile_dotfiles
}

update_straight_lockfile
