version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.10
    steps:
      - run: apt-get update -qq && apt-get install --yes curl git
      - run: curl https://cohei.github.io/dotfiles/install.sh | bash
