version: 2.1
jobs:
  local-install-test:
    machine: true
    steps:
      - run: echo $DOCKER_HUB_TOKEN | docker login --username $DOCKER_HUB_USER --password-stdin
      - checkout
      - run: docker-compose run development /home/docker/src/github.com/cohei/dotfiles/install.sh
  network-install-test:
    machine: true
    steps:
      - run: echo $DOCKER_HUB_TOKEN | docker login --username $DOCKER_HUB_USER --password-stdin
      - checkout
      - run: docker-compose up test
workflows:
  version: 2
  testing:
    jobs:
      - local-install-test:
          context:
            - docker-hub-creds
      - network-install-test:
          filters:
            branches:
              only:
                - master
          context:
            - docker-hub-creds
