version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  local-install-test:
    machine: true
    steps:
      - docker/check:
          docker-username: DOCKER_HUB_USER
          docker-password: DOCKER_HUB_TOKEN
      - checkout
      - run: docker-compose run development ./install.sh .
  network-install-test:
    machine: true
    steps:
      - docker/check:
          docker-username: DOCKER_HUB_USER
          docker-password: DOCKER_HUB_TOKEN
      - checkout
      - run: docker-compose run development sh -c 'set -o pipefail; nix run nixpkgs#wget -- -O- https://dotfiles.cohei.me | sh'
workflows:
  version: 2
  testing:
    jobs:
      - local-install-test:
          context:
            - docker-hub-creds
      - network-install-test:
          filters:
            branches:
              only:
                - master
          context:
            - docker-hub-creds
