version: 2.1
executors:
  nix:
    docker:
      - image: nixos/nix
        environment:
          TERM: xterm
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_TOKEN
jobs:
  local-install-test:
    executor: nix
    steps:
      - checkout
      - run: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - run: ./install.sh
  network-install-test:
    executor: nix
    steps:
      - checkout
      - run: echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
      - run: |
          set -o pipefail
          wget -O- https://dotfiles.cohei.me | sh
workflows:
  version: 2
  testing:
    jobs:
      - local-install-test:
          context:
            - docker-hub-creds
      - network-install-test:
          filters:
            branches:
              only:
                - master
          context:
            - docker-hub-creds
