[bookmarks]
search_depth = 100

[[module]]
type = "Symbol"
symbol = ""
color = "White"

[[module]]
type = "Bookmarks"
color = "White"
surround_with_quotes = false

[[module]]
type = "State"

[module.conflict]
text = "(conflict)"
color = "Red"

[module.divergent]
text = "(divergent)"
color = "Red"

[module.empty]
text = "(empty)"
color = "Green"

[module.immutable]
text = "(immutable)"
color = "Cyan"

[module.hidden]
text = "(hidden)"
color = "White"

[[module]]
type = "Metrics"
template = "{changed} {added} {removed}"
hide_if_empty = true

[module.changed_files]
prefix = "△"
color = "Blue"
