[bookmarks]
search_depth = 100

[[module]]
type = "Symbol"
symbol = ""
color = "White"

[[module]]
type = "Bookmarks"
color = "White"
surround_with_quotes = false

[[module]]
type = "State"

[module.conflict]
text = "(CONFLICT)"
color = "Red"

[module.divergent]
text = "(DIVERGENT)"
color = "Cyan"

[module.empty]
text = "(EMPTY)"
color = "Yellow"

[module.immutable]
text = "(IMMUTABLE)"
color = "Yellow"

[module.hidden]
text = "(HIDDEN)"
color = "Yellow"

[[module]]
type = "Metrics"
template = "{changed} {added} {removed}"
hide_if_empty = true

[module.changed_files]
prefix = "△"
color = "Blue"
