"$schema" = 'https://starship.rs/config-schema.json'

format = "[$all](bright-black)"

[aws]
style = "white"

[character]
success_symbol = "[❯](white)"

[cmd_duration]
show_notifications = true

[directory]
style = "white"

[direnv]
disabled = false
format ='$symbol[$loaded/$allowed]($style) '
style = "white"

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
style = "white"
format = "on [$symbol$branch]($style) "

[git_commit]
style = "white"

[git_metrics]
disabled = false

[git_state]
style = "bold white"

[git_status]
style = "white"

[haskell]
style = "white"

[java]
style = "white"

[nix_shell]
style = "white"
heuristic = true

[nodejs]
style = "white"

[purescript]
style = "white"

[ruby]
style = "white"

[scala]
style = "white"

[terraform]
style = "white"

[custom.jujutsu]
when = "jj root"
symbol = "jj "
