name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # runs weekly on Saturday at 00:00

jobs:
  update-flake-lock:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@7bd03711494f032dfa3be3558f7dc8787b0be333 # v3.1.0
        id: app-token
        with:
          client-id: ${{ vars.UPDATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.UPDATE_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }} # to trigger CI on PRs created by update-flake-inputs
      - uses: NixOS/nix-installer-action@150c96d08a3d21bb02f70cd1e06c830e65ac5cfc # main
      - uses: Mic92/update-flake-inputs@1e056167bd2101e587bd39deb2f64909b4759652 # v1.0.4
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          pr-labels: 'dependencies,autorebase:opt-in'
          auto-merge: 'true'
          auto-merge-method: 'REBASE'
